### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Meena-Kaling** [PiggyMouth/MPC-CBF_for_ADS#2]
Hi,

I am trying to run the program acc_with_cbf_mpc_kf.py but I encounter the following error. Could you please help me with the same? Thank you!

python acc_with_cbf_mpc_kf.py
pygame 2.5.2 (SDL 2.28.3, Python 3.8.18)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: listening to server 192.168.10.243:2000

Welcome to CARLA manual control.

Use ARROWS or WASD keys for control.

    W            : throttle
    S            : brake
    AD           : steer
    Q            : toggle reverse
    Space        : hand-brake
    P            : toggle autopilot

    TAB          : change sensor position
    `            : next sensor
    [1-9]        : change to sensor [1-9]
    C            : change weather (Shift+C reverse)
    Backspace    : change vehicle

    R            : toggle recording images to disk

    F1           : toggle HUD
    H/?          : toggle help
    ESC          : quit

ERROR: float division by zero
Traceback (most recent call last):
  File "acc_with_cbf_mpc_kf.py", line 873, in game_loop
    world = World(client.get_world(), hud)
RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to 192.168.10.243:2000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acc_with_cbf_mpc_kf.py", line 1103, in main
    game_loop(args)
  File "acc_with_cbf_mpc_kf.py", line 1029, in game_loop
    state_control(ut, dt, T)
  File "acc_with_cbf_mpc_kf.py", line 274, in state_control
    t = np.arange(0, T, dt)
ZeroDivisionError: float division by zero

Also, the output of scenario_runner is given below:

python scenario_runner.py --scenario FollowLeadingVehicle_5 --reloadWorld --output
scenario_runner.py:31: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
scenario_runner.py:94: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.13'):
INFO:  Found the required file in cache!  Carla/Maps/TM/Town04.bin
Preparing scenario: FollowLeadingVehicle_5
ScenarioManager: Running scenario FollowVehicle

 ======= Results of Scenario: FollowVehicle ---- TIMEOUT =======

 > Ego vehicles:
Actor(id=889, type=vehicle.lincoln.mkz_2017);

 > Other actors:
Actor(id=890, type=vehicle.nissan.patrol);

 > Simulation Information
╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2023-09-28 12:01:56 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2023-09-28 12:03:57 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 120.1s              │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 120.01s             │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.999s              │
╘═════════════════════════════════╧═════════════════════╛

 > Criteria Information
╒═══════════════════════════╤══════════════════════╤═════════╤══════════════╤════════════════╕
│ Actor                     │ Criterion            │ Result  │ Actual Value │ Expected Value │
├───────────────────────────┼──────────────────────┼─────────┼──────────────┼────────────────┤
│ lincoln.mkz_2017 (id=889) │ CollisionTest (Req.) │ SUCCESS │ 0            │ 0              │
├───────────────────────────┼──────────────────────┼─────────┼──────────────┼────────────────┤
│                           │ Timeout (Req.)       │ FAILURE │ 120.01       │ 120            │
├───────────────────────────┼──────────────────────┼─────────┼──────────────┼────────────────┤
│                           │ GLOBAL RESULT        │ TIMEOUT │              │                │
╘═══════════════════════════╧══════════════════════╧═════════╧══════════════╧════════════════╛
 ===============================================================

Not all scenario tests were successful
No more scenarios .... Exiting

**Comment by PiggyMouth** [comment]
Looking at your scenario_runner output it looks like the vehicle was running but did anything happen in the end with the simulatrion that caused a timeout? 
Zero division seems to be caused by the simulation timeout which stopped you from saving the plot result of the simulation since the timestamp T is based on how long your simulation Hud was active.
